import type { ToolEmitter, RuleSection, ScanResult, EmitResult } from '../types.js';
import { GENERATED_HEADER } from '../types.js';
import { sectionsToMarkdown } from './markdown.js';

const OUTPUT_PATH = '.cursor/rules/airules.mdc';

export const cursorEmitter: ToolEmitter = {
  id: 'cursor',
  name: 'Cursor',
  outputPath: OUTPUT_PATH,
  emit(sections: RuleSection[], _scan: ScanResult): EmitResult[] {
    const frontmatter = [
      '---',
      'description: "Project rules generated by airules"',
      'alwaysApply: true',
      '---',
      '',
    ].join('\n');

    const body = sectionsToMarkdown(sections, 'Cursor Rules');
    return [{ path: OUTPUT_PATH, content: frontmatter + body }];
  },
};
