import type { ToolEmitter, RuleSection, ScanResult, EmitResult } from '../types.js';
import { GENERATED_HEADER } from '../types.js';
import { sectionsToMarkdown } from './markdown.js';

const OUTPUT_PATH = '.roo/rules/airules.md';

export const rooEmitter: ToolEmitter = {
  id: 'roo',
  name: 'Roo Code',
  outputPath: OUTPUT_PATH,
  emit(sections: RuleSection[], _scan: ScanResult): EmitResult[] {
    const frontmatter = [
      '---',
      'description: "Project rules generated by airules"',
      '---',
      '',
    ].join('\n');

    const body = sectionsToMarkdown(sections, 'Roo Code Rules');
    return [{ path: OUTPUT_PATH, content: frontmatter + body }];
  },
};
