import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import YAML from 'yaml';
import type { AirulesConfig } from '../types.js';

const CONFIG_FILENAME = '.airules.yaml';

/**
 * Loads .airules.yaml config from the project root.
 * Returns undefined if no config file exists.
 */
export async function loadConfig(projectRoot: string): Promise<AirulesConfig | undefined> {
  const configPath = join(projectRoot, CONFIG_FILENAME);
  try {
    const raw = await readFile(configPath, 'utf-8');
    const parsed = YAML.parse(raw) as AirulesConfig;
    return parsed ?? undefined;
  } catch {
    return undefined;
  }
}

/**
 * Writes .airules.yaml config to the project root.
 */
export async function saveConfig(projectRoot: string, config: AirulesConfig): Promise<void> {
  const configPath = join(projectRoot, CONFIG_FILENAME);
  const header = '# Generated by airulegen. Customize as needed.\n# Run `npx airulegen sync` to regenerate rule files from this config.\n\n';
  const content = header + YAML.stringify(config, { indent: 2, lineWidth: 120 });
  await writeFile(configPath, content, 'utf-8');
}
