// === Core Types ===

export interface ScanResult {
  language: 'typescript' | 'javascript' | 'python' | 'go' | 'rust' | 'ruby' | 'java' | 'unknown';
  framework: string | null;        // 'nextjs', 'react', 'vue', 'fastapi', 'express', etc.
  packageManager: string | null;   // 'npm', 'pnpm', 'yarn', 'bun', 'pip', 'cargo', etc.
  styling: string | null;          // 'tailwind', 'css-modules', 'styled-components', etc.
  testing: string | null;          // 'vitest', 'jest', 'pytest', 'go-test', etc.
  orm: string | null;              // 'prisma', 'drizzle', 'sqlalchemy', etc.
  monorepo: boolean;               // turborepo, nx, pnpm workspaces
  directories: string[];           // detected important dirs: src/, app/, pages/, etc.
  dependencies: Record<string, string>;  // key deps with versions
}

export interface RuleSection {
  id: string;                      // unique ID: 'general', 'coding-style', 'testing', etc.
  title: string;                   // human-readable title
  content: string;                 // markdown content (the actual rules)
  scope?: string;                  // glob pattern for conditional rules
  priority: 'high' | 'medium' | 'low';
  tags: string[];                  // for filtering: ['style', 'testing', 'security']
}

export interface Preset {
  id: string;                      // 'nextjs', 'react', 'fastapi', etc.
  name: string;                    // 'Next.js'
  description: string;
  detect: (scan: ScanResult) => boolean;    // auto-detection function
  sections: (scan: ScanResult) => RuleSection[];  // generate rules
}

export interface ToolEmitter {
  id: string;                      // 'claude', 'cursor', etc.
  name: string;                    // 'Claude Code'
  outputPath: string | ((projectRoot: string) => string);
  emit: (sections: RuleSection[], scan: ScanResult) => EmitResult[];
}

export interface EmitResult {
  path: string;                    // relative path from project root
  content: string;                 // file content to write
}

export interface AirulesConfig {
  version?: number;
  tools?: string[];                // which tools to generate for (default: all)
  presets?: string[];              // additional presets to include
  exclude?: string[];              // presets to exclude
  rules?: RuleSection[];           // additional custom rules
  detected?: Partial<ScanResult>;  // stored scan result
  custom?: CustomRule[];           // custom user rules
}

export interface CustomRule {
  title: string;
  content: string;
}

export const GENERATED_HEADER = '<!-- Generated by airulegen. Do not edit manually. Run `npx airulegen sync` to regenerate. -->';
